sudo: required

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "rpg-dice-api"
  env: "RpgDiceApi-env"
  bucket: "elasticbeanstalk-us-east-2-304614639558"
  bucket_path: "rpg-dice-api"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    tags: true
